call ADDON_fnc_distance_patch;
call ADDON_fnc_createFlag_patch;

call A3A_fnc_initServer;

call ADDON_fnc_getSoftTargets_patch;
call ADDON_fnc_getTargetsAT_patch;
call ADDON_fnc_autoEquipDrones;
call ADDON_fnc_autoReloadUnits;

call ADDON_fnc_kmd_moveInConvoyInit;
call ADDON_fnc_kmd_addToHcExecute_patch;
call ADDON_fnc_kmd_addToHc_patch;
call ADDON_fnc_kmd_spawnGetOutVehicle_patch;

call ADDON_fnc_getCargoConfig_patch;

call ADDON_fnc_sellVehicle_patch;

call ADDON_fnc_postmortem_patch;
call ADDON_fnc_enemyGarrison_patch;
call ADDON_fnc_groupDespawner_patch;
call ADDON_fnc_surrenderAction_patch;


