//////
//
// The SQF code is generated by atscc2sqf
// The starting compilation time is: //
//////
atscc2sqf_unit_heap = [];

//
// ATSextcode_beg()
//
ext_isBoss = {
  params [ "_unit"];
  _unit == theBoss;
};
//
// ATSextcode_end()
//

//
// ATSextcode_beg()
//
ext_libarma3_HR_GRG_fnc_confirmPlacement = {
  params [ "_class_name" , "_on_placed", "_env", "_extra_text"];
  [_class_name, _on_placed, _env, nil, nil, nil, _extra_text]
    call HR_GRG_fnc_confirmPlacement;
};
//
// ATSextcode_end()
//

//
// ATSextcode_beg()
//
ext_ADDON_fnc_isAdministration = {
  params ["_unit"];
  [ _unit ] call ADDON_fnc_isAdministration;
};
//
// ATSextcode_end()
//

//
// ATSextcode_beg()
//
ext_commander = {
  petros;
};
//
// ATSextcode_end()
//

/*fun*/
/*emit_f0ide*/ fn_addon__ensure_not_null = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret0
private _Tmpret0 = 0;
// var _Tmp1
private _Tmp1 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_ensure_not_null /*ATSINSflab*/ ;
  _Tmp1 = [ _Arg0] call /*emit_f0ide*/ libarma3__isNotNull;
  if (_Tmp1) then {
      _Tmpret0 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
    } // if-then
    else {
      _Tmpret0 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */
    // if-else
    };
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret0;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__ensure_boss = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret2
private _Tmpret2 = 0;
// var _Tmp3
private _Tmp3 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_ensure_boss /*ATSINSflab*/ ;
  _Tmp3 = [ _Arg0] call /*emit_f0ide*/ fn_addon__isBoss;
  if (_Tmp3) then {
      _Tmpret2 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
    } // if-then
    else {
      _Tmpret2 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */
    // if-else
    };
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret2;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__ensure_administrator = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret4
private _Tmpret4 = 0;
// var _Tmp5
private _Tmp5 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_ensure_administrator /*ATSINSflab*/ ;
  _Tmp5 = [ _Arg0] call /*emit_f0ide*/ fn_addon__ADDON_fnc_isAdministration;
  if (_Tmp5) then {
      _Tmpret4 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
    } // if-then
    else {
      _Tmpret4 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */
    // if-else
    };
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret4;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__isBoss = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret6
private _Tmpret6 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_isBoss /*ATSINSflab*/ ;
  _Tmpret6 = [ _Arg0] call /*emit_f0ide*/ ext_isBoss;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret6;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__HR_GRG_fnc_confirmPlacement = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var _Tmp10
private _Tmp10 = 0;
// var _Tmp11
private _Tmp11 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_HR_GRG_fnc_confirmPlacement /*ATSINSflab*/ ;
   /*ATSINSmove_void _*/ /*D0Eappexp ATSfunclo_fun*/[_Arg0] call /*ATSfunclo_fun*/ text__lemma_text_param;
   /*ATSINSmove_void _*/ /*D0Eappexp ATSfunclo_fun*/[_Arg3] call /*ATSfunclo_fun*/ text__lemma_text_param;
  _Tmp10 = [ _Arg0] call /*emit_f0ide*/ text__text2string;
  _Tmp11 = [ _Arg3] call /*emit_f0ide*/ text__text2string;
   /*ATSINSmove_void _*/[ _Tmp10, _Arg1, _Arg2, _Tmp11] call /*emit_f0ide*/ ext_libarma3_HR_GRG_fnc_confirmPlacement;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__ADDON_fnc_isAdministration = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret12
private _Tmpret12 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_ADDON_fnc_isAdministration /*ATSINSflab*/ ;
  _Tmpret12 = [ _Arg0] call /*emit_f0ide*/ ext_ADDON_fnc_isAdministration;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret12;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__commander = compileFinal {
//
// knd = 0
// var _Tmpret13
private _Tmpret13 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_commander /*ATSINSflab*/ ;
  _Tmpret13 = [ ] call /*emit_f0ide*/ ext_commander;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret13;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_addon__main = compileFinal {
//
// knd = 0
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_main /*ATSINSflab*/ ;
  ; // ATSINSmove_void();
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function

atscc2sqf_unit_heap resize 1;
_this call fn_addon__main;
//////
////// defined but not used: 
// fn_addon__main
// fn_addon__commander
// fn_addon__HR_GRG_fnc_confirmPlacement
// fn_addon__ensure_administrator
// fn_addon__ensure_boss
// fn_addon__ensure_not_null
////// called external functions: 
// ext_commander
// ext_ADDON_fnc_isAdministration
// ext_libarma3_HR_GRG_fnc_confirmPlacement
// ext_isBoss
////// called undefined functions: 
// text__text2string
// libarma3__isNotNull
// end-of-compilation-unit
//
//////
