//////
//
// The SQF code is generated by atscc2sqf
// The starting compilation time is: //
//////
atscc2sqf_unit_heap = [];

/*fun*/
/*emit_f0ide*/ fn_initServer__main = compileFinal {
//
// knd = 0
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_main /*ATSINSflab*/ ;
   /*ATSINSmove_void _*/[ ] call /*emit_f0ide*/ fn_persistentUserMarkers__initServer;
   /*ATSINSmove_void _*/[ ] call /*emit_f0ide*/ fn_support__initServer;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function

atscc2sqf_unit_heap resize 1;
_this call fn_initServer__main;
//////
////// defined but not used: 
// fn_initServer__main
////// called external functions: 
////// called undefined functions: 
// fn_support__initServer
// fn_persistentUserMarkers__initServer
// end-of-compilation-unit
//
//////
