//////
//
// The SQF code is generated by atscc2sqf
// The starting compilation time is: //
//////
atscc2sqf_unit_heap = [];

/*fun*/
/*emit_f0ide*/ init_client_0 = compileFinal {
//
// knd = 0
// var _Tmp1
private _Tmp1 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_init_client_0 /*ATSINSflab*/ ;
  _Tmp1 = [ "hello world"] call /*emit_f0ide*/ text__pack_string;
   /*ATSINSmove_void _*/[ _Tmp1] call /*emit_f0ide*/ libarma3__systemChat;
   /*ATSINSmove_void _*/[ _Tmp1] call /*emit_f0ide*/ text__free_text;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__main = compileFinal {
//
// knd = 0
// var _Tmp4
private _Tmp4 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_main /*ATSINSflab*/ ;
  _Tmp4 = [ ] call /*emit_f0ide*/ ext_libarma3_isServer;
  if (_Tmp4) then {
      ; // ATSINSmove_void();
    } // if-then
    else {
       /*ATSINSmove_void _*/[ ] call /*emit_f0ide*/ init_client_0
    // if-else
    };
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function

atscc2sqf_unit_heap resize 1;
_this call fn_support__main;
//////
////// defined but not used: 
// fn_support__main
////// called external functions: 
// ext_libarma3_isServer
////// called undefined functions: 
// text__free_text
// libarma3__systemChat
// text__pack_string
// end-of-compilation-unit
//
//////
