//////
//
// The SQF code is generated by atscc2sqf
// The starting compilation time is: //
//////
atscc2sqf_unit_heap = [];

/*fun*/
/*emit_f0ide*/ fn_support__addActions = compileFinal {
//
// knd = 0
// var _Tmp1
private _Tmp1 = 0;
// var _Tmp2
private _Tmp2 = 0;
// var _Tmp3
private _Tmp3 = 0;
// var _Tmp4
private _Tmp4 = 0;
// var _Tmp5
private _Tmp5 = 0;
// var _Tmp6
private _Tmp6 = 0;
// var _Tmp7
private _Tmp7 = 0;
// var _Tmp8
private _Tmp8 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_addActions /*ATSINSflab*/ ;
  _Tmp1 = [ ] call /*emit_f0ide*/ fn_addon__commander;
  _Tmp2 = [ ] call /*emit_f0ide*/ libarma3__player;
  _Tmp4 = [ "STR_support_request_support"] call /*emit_f0ide*/ text__pack_string;
  _Tmp3 = [ _Tmp4] call /*emit_f0ide*/ libarma3__localize;
  _Tmp6 = [ "STR_support_editor"] call /*emit_f0ide*/ text__pack_string;
  _Tmp5 = [ _Tmp6] call /*emit_f0ide*/ libarma3__localize;
  _Tmp7 = [ _Tmp1, _Tmp3, fn_support__requestSupport_action, 0, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
  _Tmp8 = [ _Tmp1, _Tmp5, fn_support__supportEditor_action, 0, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
   /*ATSINSmove_void _*/[ _Tmp3] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp5] call /*emit_f0ide*/ text__free_text;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__supportEditor_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var _Tmp35
private _Tmp35 = 0;
// var _Tmp36
private _Tmp36 = 0;
// var _Tmp37
private _Tmp37 = 0;
// var _Tmp38
private _Tmp38 = 0;
// var _Tmp42
private _Tmp42 = 0;
// var _Tmp44
private _Tmp44 = 0;
// var _Tmp45
private _Tmp45 = 0;
// var _Tmp46
private _Tmp46 = 0;
// var _Tmp48
private _Tmp48 = 0;
// var _Tmp49
private _Tmp49 = 0;
// var _Tmp50
private _Tmp50 = 0;
// var _Tmp52
private _Tmp52 = 0;
// var _Tmp53
private _Tmp53 = 0;
// var _Tmp54
private _Tmp54 = 0;
// var _Tmp56
private _Tmp56 = 0;
// var _Tmp57
private _Tmp57 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_supportEditor_action /*ATSINSflab*/ ;
  _Tmp38 = [0, _Arg1];
  _Tmp37 = [ _Tmp38, /*emit_f0ide*/ f___patsfun_3, fn_addon__ensure_not_null] call /*emit_f0ide*/ result_vb__withExcept;
  _Tmp36 = [ _Tmp37, /*emit_f0ide*/ f___patsfun_4] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp35 = [ _Tmp36, /*emit_f0ide*/ add_actions_verified_2] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp35 select 0) == 0)) then {
          _Tmp50 = (_Tmp35 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp42 = (_Tmp35 select 1);
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp44 = /* ATSSELfltrec */ (_Tmp42 select 1);
         [ _Casefun, 3 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 3 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp44 select 0) == 0)) then {
          _Tmp46 = _Tmp42;
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp45 = (_Tmp44 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp44);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp35);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp54 = [ "STR_support_caller_null"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp53 = [ _Tmp54] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp53] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp53] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp35 select 0) == 0)) then {
          _Tmp50 = (_Tmp35 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp46 = (_Tmp35 select 1);
           [ _Casefun, 6 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 6 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp48 = /* ATSSELfltrec */ (_Tmp46 select 1);
         [ _Casefun, 7 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 7 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp48 select 0) == 1)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 4101(line=121, offs=3) -- 4958(line=142, offs=6)");
        } else {
           [ _Casefun, 8 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 8 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp49 = (_Tmp48 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp48);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp35);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp57 = [ "STR_persistentUserMarkers_only_administrator_can_do_this"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp56 = [ _Tmp57] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp56] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp56] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp35 select 0) == 1)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 4101(line=121, offs=3) -- 4958(line=142, offs=6)");
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp50 = (_Tmp35 select 1);
           [ _Casefun, 10 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 10 : {
         [ _Casefun, 11 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 11 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp52 = /* ATSSELfltrec */ (_Tmp50 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp35);;
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ add_actions_verified_2 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret11
private _Tmpret11 = 0;
// var _Tmp12
private _Tmp12 = 0;
// var _Tmp13
private _Tmp13 = 0;
// var _Tmp14
private _Tmp14 = 0;
// var _Tmp15
private _Tmp15 = 0;
// var _Tmp16
private _Tmp16 = 0;
// var _Tmp17
private _Tmp17 = 0;
// var _Tmp18
private _Tmp18 = 0;
// var _Tmp19
private _Tmp19 = 0;
// var _Tmp20
private _Tmp20 = 0;
// var _Tmp21
private _Tmp21 = 0;
// var _Tmp22
private _Tmp22 = 0;
// var _Tmp23
private _Tmp23 = 0;
// var _Tmp24
private _Tmp24 = 0;
// var _Tmp34
private _Tmp34 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_add_actions_verified_2 /*ATSINSflab*/ ;
  _Tmp12 = /* ATSSELfltrec */ (_Arg0 select 1);
  _Tmp14 = [ "STR_support_add_vehicle_to_support"] call /*emit_f0ide*/ text__pack_string;
  _Tmp13 = [ _Tmp14] call /*emit_f0ide*/ libarma3__localize;
  _Tmp15 = [ "fn_support_addVehicleToSupportActionId"] call /*emit_f0ide*/ text__pack_string;
  _Tmp17 = [ "STR_support_delete_vehicle_from_support"] call /*emit_f0ide*/ text__pack_string;
  _Tmp16 = [ _Tmp17] call /*emit_f0ide*/ libarma3__localize;
  _Tmp18 = [ "fn_support_deleteVehicleFromSupportActionId"] call /*emit_f0ide*/ text__pack_string;
  _Tmp20 = [ "STR_support_exit_support_editor"] call /*emit_f0ide*/ text__pack_string;
  _Tmp19 = [ _Tmp20] call /*emit_f0ide*/ libarma3__localize;
  _Tmp21 = [ "fn_support_exitSupportEditorActionId"] call /*emit_f0ide*/ text__pack_string;
  _Tmp22 = [ _Tmp12, _Tmp13, fn_support__addVehicleToSupport_action, 0, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
  _Tmp23 = [ _Tmp12, _Tmp16, fn_support__deleteVehicleFromSupport_action, 0, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
  _Tmp24 = [ _Tmp12, _Tmp19, fn_support__exitSupportEditor_action, 0, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
   /*ATSINSmove_void _*/[ _Tmp12, _Tmp15, _Tmp22, false] call /*emit_f0ide*/ libarma3__setVariable;
   /*ATSINSmove_void _*/[ _Tmp12, _Tmp18, _Tmp23, false] call /*emit_f0ide*/ libarma3__setVariable;
   /*ATSINSmove_void _*/[ _Tmp12, _Tmp21, _Tmp24, false] call /*emit_f0ide*/ libarma3__setVariable;
   /*ATSINSmove_void _*/[ _Tmp13] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp15] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp16] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp18] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp19] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp21] call /*emit_f0ide*/ text__free_text;
  _Tmp34 = [0, _Tmp12];
  _Tmpret11 = [ 1, _Tmp34 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret11;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_3 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret39
private _Tmpret39 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_3 /*ATSINSflab*/ ;
  _Tmpret39 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret39;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_4 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret40
private _Tmpret40 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_4 /*ATSINSflab*/ ;
  _Tmpret40 = [ _Arg0, /*emit_f0ide*/ f___patsfun_5, fn_addon__ensure_administrator] call /*emit_f0ide*/ result_vb__withExcept;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret40;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_5 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret41
private _Tmpret41 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_5 /*ATSINSflab*/ ;
  _Tmpret41 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret41;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__exitSupportEditor_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var _Tmp67
private _Tmp67 = 0;
// var _Tmp68
private _Tmp68 = 0;
// var _Tmp69
private _Tmp69 = 0;
// var _Tmp70
private _Tmp70 = 0;
// var _Tmp71
private _Tmp71 = 0;
// var _Tmp72
private _Tmp72 = 0;
// var _Tmp73
private _Tmp73 = 0;
// var _Tmp74
private _Tmp74 = 0;
// var _Tmp103
private _Tmp103 = 0;
// var _Tmp105
private _Tmp105 = 0;
// var _Tmp107
private _Tmp107 = 0;
// var _Tmp109
private _Tmp109 = 0;
// var _Tmp111
private _Tmp111 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_exitSupportEditor_action /*ATSINSflab*/ ;
  _Tmp74 = [0, _Arg1];
  _Tmp73 = [ _Tmp74, /*emit_f0ide*/ f___patsfun_8, fn_addon__ensure_not_null] call /*emit_f0ide*/ result_vb__withExcept;
  _Tmp72 = [ _Tmp73, /*emit_f0ide*/ f___patsfun_9] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp71 = [ _Tmp72, /*emit_f0ide*/ removeAction_verified_7] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp70 = [ _Tmp71, /*emit_f0ide*/ f___patsfun_12] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp69 = [ _Tmp70, /*emit_f0ide*/ removeAction_verified_7] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp68 = [ _Tmp69, /*emit_f0ide*/ f___patsfun_15] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp67 = [ _Tmp68, /*emit_f0ide*/ removeAction_verified_7] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp67 select 0) == 0)) then {
          _Tmp111 = (_Tmp67 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp103 = (_Tmp67 select 1);
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp105 = /* ATSSELfltrec */ (_Tmp103 select 1);
         [ _Casefun, 3 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 3 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp105 select 0) == 0)) then {
          _Tmp107 = _Tmp103;
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp105);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp67);;
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp67 select 0) == 0)) then {
          _Tmp111 = (_Tmp67 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp107 = (_Tmp67 select 1);
           [ _Casefun, 6 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 6 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp109 = /* ATSSELfltrec */ (_Tmp107 select 1);
         [ _Casefun, 7 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 7 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp109 select 0) == 1)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 13510(line=347, offs=3) -- 13974(line=359, offs=4)");
        } else {
           [ _Casefun, 8 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 8 : {
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp109);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp67);;
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp67 select 0) == 1)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 13510(line=347, offs=3) -- 13974(line=359, offs=4)");
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp111 = (_Tmp67 select 1);
           [ _Casefun, 10 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 10 : {
         [ _Casefun, 11 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 11 : {
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp67);;
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ removeAction_verified_7 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret60
private _Tmpret60 = 0;
// var _Tmp61
private _Tmp61 = 0;
// var _Tmp62
private _Tmp62 = 0;
// var _Tmp63
private _Tmp63 = 0;
// var _Tmp64
private _Tmp64 = 0;
// var _Tmp66
private _Tmp66 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_removeAction_verified_7 /*ATSINSflab*/ ;
  _Tmp61 = /* ATSSELfltrec */ (_Arg0 select 1);
  _Tmp62 = /* ATSSELfltrec */ (_Arg0 select 0);
  _Tmp63 = /* ATSSELfltrec */ (_Tmp61 select 0);
  _Tmp64 = /* ATSSELfltrec */ (_Tmp61 select 1);
   /*ATSINSmove_void _*/[ _Tmp63, _Tmp64] call /*emit_f0ide*/ libarma3__removeAction;
  _Tmp66 = [0, _Tmp63];
  _Tmpret60 = [ 1, _Tmp66 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret60;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_8 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret75
private _Tmpret75 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_8 /*ATSINSflab*/ ;
  _Tmpret75 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret75;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_9 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret76
private _Tmpret76 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_9 /*ATSINSflab*/ ;
  _Tmpret76 = [ _Arg0, /*emit_f0ide*/ f___patsfun_10, /*emit_f0ide*/ f___patsfun_11] call /*emit_f0ide*/ result_vb__withExcept;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret76;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_10 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret77
private _Tmpret77 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_10 /*ATSINSflab*/ ;
  _Tmpret77 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret77;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_11 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret78
private _Tmpret78 = 0;
// var _Tmp79
private _Tmp79 = 0;
// var _Tmp80
private _Tmp80 = 0;
// var _Tmp81
private _Tmp81 = 0;
// var _Tmp84
private _Tmp84 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_11 /*ATSINSflab*/ ;
  _Tmp79 = [ "fn_support_addVehicleToSupportActionId"] call /*emit_f0ide*/ text__pack_string;
  _Tmp80 = [ _Arg0, _Tmp79] call /*emit_f0ide*/ libarma3__getVariable1;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(/*ATSCKptriscons*/ (not(isNil { _Tmp80 select 0 } )) ) then {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        } else {
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp79] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret78 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3 : {
        if(/*ATSCKptrisnull*/ ( isNil { _Tmp80 select 0 }) ) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 9456(line=266, offs=27) -- 10070(line=276, offs=26)");
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp81 = (_Tmp80 select 0);
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp79] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp84 = [_Arg0, _Tmp81];
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret78 = [ 1, _Tmp84 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret78;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_12 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret85
private _Tmpret85 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_12 /*ATSINSflab*/ ;
  _Tmpret85 = [ _Arg0, /*emit_f0ide*/ f___patsfun_13, /*emit_f0ide*/ f___patsfun_14] call /*emit_f0ide*/ result_vb__withExcept;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret85;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_13 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret86
private _Tmpret86 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_13 /*ATSINSflab*/ ;
  _Tmpret86 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret86;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_14 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret87
private _Tmpret87 = 0;
// var _Tmp88
private _Tmp88 = 0;
// var _Tmp89
private _Tmp89 = 0;
// var _Tmp90
private _Tmp90 = 0;
// var _Tmp93
private _Tmp93 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_14 /*ATSINSflab*/ ;
  _Tmp88 = [ "fn_support_deleteVehicleFromSupportActionId"] call /*emit_f0ide*/ text__pack_string;
  _Tmp89 = [ _Arg0, _Tmp88] call /*emit_f0ide*/ libarma3__getVariable1;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(/*ATSCKptriscons*/ (not(isNil { _Tmp89 select 0 } )) ) then {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        } else {
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp88] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret87 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3 : {
        if(/*ATSCKptrisnull*/ ( isNil { _Tmp89 select 0 }) ) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 10797(line=293, offs=27) -- 11426(line=303, offs=26)");
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp90 = (_Tmp89 select 0);
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp88] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp93 = [_Arg0, _Tmp90];
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret87 = [ 1, _Tmp93 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret87;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_15 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret94
private _Tmpret94 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_15 /*ATSINSflab*/ ;
  _Tmpret94 = [ _Arg0, /*emit_f0ide*/ f___patsfun_16, /*emit_f0ide*/ f___patsfun_17] call /*emit_f0ide*/ result_vb__withExcept;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret94;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_16 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret95
private _Tmpret95 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_16 /*ATSINSflab*/ ;
  _Tmpret95 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret95;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_17 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret96
private _Tmpret96 = 0;
// var _Tmp97
private _Tmp97 = 0;
// var _Tmp98
private _Tmp98 = 0;
// var _Tmp99
private _Tmp99 = 0;
// var _Tmp102
private _Tmp102 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_17 /*ATSINSflab*/ ;
  _Tmp97 = [ "fn_support_exitSupportEditorActionId"] call /*emit_f0ide*/ text__pack_string;
  _Tmp98 = [ _Arg0, _Tmp97] call /*emit_f0ide*/ libarma3__getVariable1;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(/*ATSCKptriscons*/ (not(isNil { _Tmp98 select 0 } )) ) then {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        } else {
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp97] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret96 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3 : {
        if(/*ATSCKptrisnull*/ ( isNil { _Tmp98 select 0 }) ) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 12165(line=320, offs=27) -- 12773(line=330, offs=26)");
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp99 = (_Tmp98 select 0);
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp97] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp102 = [_Arg0, _Tmp99];
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret96 = [ 1, _Tmp102 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret96;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__requestSupport_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var _Tmp192
private _Tmp192 = 0;
// var _Tmp193
private _Tmp193 = 0;
// var _Tmp194
private _Tmp194 = 0;
// var _Tmp195
private _Tmp195 = 0;
// var _Tmp196
private _Tmp196 = 0;
// var _Tmp200
private _Tmp200 = 0;
// var _Tmp202
private _Tmp202 = 0;
// var _Tmp203
private _Tmp203 = 0;
// var _Tmp204
private _Tmp204 = 0;
// var _Tmp206
private _Tmp206 = 0;
// var _Tmp207
private _Tmp207 = 0;
// var _Tmp208
private _Tmp208 = 0;
// var _Tmp210
private _Tmp210 = 0;
// var _Tmp211
private _Tmp211 = 0;
// var _Tmp212
private _Tmp212 = 0;
// var _Tmp214
private _Tmp214 = 0;
// var _Tmp215
private _Tmp215 = 0;
// var _Tmp216
private _Tmp216 = 0;
// var _Tmp218
private _Tmp218 = 0;
// var _Tmp219
private _Tmp219 = 0;
// var _Tmp221
private _Tmp221 = 0;
// var _Tmp222
private _Tmp222 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_requestSupport_action /*ATSINSflab*/ ;
  _Tmp196 = [0, _Arg1];
  _Tmp195 = [ _Tmp196, /*emit_f0ide*/ f___patsfun_25, fn_addon__ensure_not_null] call /*emit_f0ide*/ result_vb__withExcept;
  _Tmp194 = [ _Tmp195, /*emit_f0ide*/ f___patsfun_26] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp193 = [ _Tmp194, /*emit_f0ide*/ get_support_vehicles_19] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp192 = [ _Tmp193, /*emit_f0ide*/ add_actions_verified_20] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp192 select 0) == 0)) then {
          _Tmp212 = (_Tmp192 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp200 = (_Tmp192 select 1);
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp202 = /* ATSSELfltrec */ (_Tmp200 select 1);
         [ _Casefun, 3 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 3 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp202 select 0) == 0)) then {
          _Tmp204 = _Tmp200;
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp203 = (_Tmp202 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp202);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp192);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp216 = [ "STR_support_caller_null"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp215 = [ _Tmp216] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp215] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp215] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp192 select 0) == 0)) then {
          _Tmp212 = (_Tmp192 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp204 = (_Tmp192 select 1);
           [ _Casefun, 6 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 6 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp206 = /* ATSSELfltrec */ (_Tmp204 select 1);
         [ _Casefun, 7 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 7 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp206 select 0) == 1)) then {
          _Tmp208 = _Tmp204;
        } else {
           [ _Casefun, 8 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 8 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp207 = (_Tmp206 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp206);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp192);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp219 = [ "STR_persistentUserMarkers_only_commander_can_do_this"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp218 = [ _Tmp219] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp218] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp218] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp192 select 0) == 0)) then {
          _Tmp212 = (_Tmp192 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp208 = (_Tmp192 select 1);
           [ _Casefun, 10 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 10 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp210 = /* ATSSELfltrec */ (_Tmp208 select 1);
         [ _Casefun, 11 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 11 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp210 select 0) == 2)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 16224(line=426, offs=3) -- 17423(line=455, offs=6)");
        } else {
           [ _Casefun, 12 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 12 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp211 = (_Tmp210 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp210);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp192);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp222 = [ "STR_support_no_requestable_support_vehicles"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp221 = [ _Tmp222] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp221] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp221] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 13 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp192 select 0) == 1)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 16224(line=426, offs=3) -- 17423(line=455, offs=6)");
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp212 = (_Tmp192 select 1);
           [ _Casefun, 14 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 14 : {
         [ _Casefun, 15 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 15 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp214 = /* ATSSELfltrec */ (_Tmp212 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp192);;
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ get_support_vehicles_19 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret115
private _Tmpret115 = 0;
// var _Tmp116
private _Tmp116 = 0;
// var _Tmp117
private _Tmp117 = 0;
// var _Tmp118
private _Tmp118 = 0;
// var _Tmp119
private _Tmp119 = 0;
// var _Tmp120
private _Tmp120 = 0;
// var _Tmp122
private _Tmp122 = 0;
// var _Tmp123
private _Tmp123 = 0;
// var _Tmp124
private _Tmp124 = 0;
// var _Tmp125
private _Tmp125 = 0;
// var _Tmp126
private _Tmp126 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_get_support_vehicles_19 /*ATSINSflab*/ ;
  _Tmp116 = /* ATSSELfltrec */ (_Arg0 select 0);
  _Tmp117 = /* ATSSELfltrec */ (_Arg0 select 1);
  _Tmp118 = [ "fn_support_request_support_vehicles"] call /*emit_f0ide*/ text__pack_string;
  _Tmp119 = [ ] call /*emit_f0ide*/ libarma3__missionNamespace;
  _Tmp120 = [ _Tmp119, _Tmp118, false] call /*emit_f0ide*/ libarma3__borrowVariable_vt1;
   /*ATSINSmove_void _*/[ _Tmp118] call /*emit_f0ide*/ text__free_text;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(/*ATSCKptriscons*/ (not(isNil { _Tmp120 select 0 } )) ) then {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        } else {
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp124 = [ 2, _Tmp117 ]/* emit2_ATSINSmove_con1 */;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp123 = [_Tmp116, _Tmp124];
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret115 = [ 0, _Tmp123 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3 : {
        if(/*ATSCKptrisnull*/ ( isNil { _Tmp120 select 0 }) ) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 19250(line=505, offs=11) -- 19727(line=515, offs=21)");
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp122 = (_Tmp120 select 0);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp120);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp126 = [_Tmp117, _Tmp122];
/*emit2_branchlst rest-of-ATSINS*/        _Tmp125 = [_Tmp116, _Tmp126];
/*emit2_branchlst rest-of-ATSINS*/        _Tmpret115 = [ 1, _Tmp125 ]/* emit2_ATSINSmove_con1 */
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret115;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ add_actions_verified_20 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret127
private _Tmpret127 = 0;
// var _Tmp128
private _Tmp128 = 0;
// var _Tmp129
private _Tmp129 = 0;
// var _Tmp130
private _Tmp130 = 0;
// var _Tmp131
private _Tmp131 = 0;
// var _Tmp132
private _Tmp132 = 0;
// var _Tmp133
private _Tmp133 = 0;
// var _Tmp134
private _Tmp134 = 0;
// var _Tmp135
private _Tmp135 = 0;
// var _Tmp165
private _Tmp165 = 0;
// var _Tmp166
private _Tmp166 = 0;
// var _Tmp167
private _Tmp167 = 0;
// var _Tmp168
private _Tmp168 = 0;
// var _Tmp169
private _Tmp169 = 0;
// var _Tmp171
private _Tmp171 = 0;
// var _Tmp172
private _Tmp172 = 0;
// var _Tmp174
private _Tmp174 = 0;
// var _Tmp175
private _Tmp175 = 0;
// var _Tmp184
private _Tmp184 = 0;
// var _Tmp187
private _Tmp187 = 0;
// var _Tmp189
private _Tmp189 = 0;
// var _Tmp191
private _Tmp191 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_add_actions_verified_20 /*ATSINSflab*/ ;
  _Tmp128 = /* ATSSELfltrec */ (_Arg0 select 1);
  _Tmp129 = /* ATSSELfltrec */ (_Tmp128 select 0);
  _Tmp130 = /* ATSSELfltrec */ (_Tmp128 select 1);
  _Tmp132 = [ 0] call /*emit_f0ide*/ atspre_g1int2uint_int_size;
  _Tmp131 = [ _Tmp132] call /*emit_f0ide*/ libarma3__array_create;
  _Tmp133 = [ "fn_support_request_support_vehicles"] call /*emit_f0ide*/ text__pack_string;
  _Tmp134 = [ ] call /*emit_f0ide*/ libarma3__missionNamespace;
  _Tmp135 = [ /* ATSSELfltrec */ (_Tmp130 select 1)] call /*emit_f0ide*/ libarma3__array_vt_count;
  _Tmp166 = [ 0] call /*emit_f0ide*/ atspre_g1int2uint_int_size;
  _Tmp165 = [ _Tmp129, _Tmp131, _Tmp129, /* ATSSELfltrec */ (_Tmp130 select 1), _Tmp135, _Tmp166] call /*emit_f0ide*/ add_per_class_support_request_in_loop_21;
  _Tmp168 = [ "STR_support_finish_support_request"] call /*emit_f0ide*/ text__pack_string;
  _Tmp167 = [ _Tmp168] call /*emit_f0ide*/ libarma3__localize;
  _Tmp169 = [ _Tmp129, _Tmp167, fn_support__finish_support_request_action, 0, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
   /*ATSINSmove_void _*/[ _Tmp165, _Tmp169] call /*emit_f0ide*/ libarma3__array_pushBack;
  _Tmp171 = [ "fn_support_remove_player_actions_ids"] call /*emit_f0ide*/ text__pack_string;
  _Tmp172 = [ _Tmp129, _Tmp171, _Tmp165, false] call /*emit_f0ide*/ libarma3__swapVariable_vt1;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(/*ATSCKptriscons*/ (not(isNil { _Tmp172 select 0 } )) ) then {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        } else {
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3 : {
        if(/*ATSCKptrisnull*/ ( isNil { _Tmp172 select 0 }) ) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 27602(line=672, offs=16) -- 29596(line=711, offs=17)");
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp174 = (_Tmp172 select 0);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp172);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp175 = [ _Tmp174] call /*emit_f0ide*/ libarma3__array_count;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp184 = [ 0] call /*emit_f0ide*/ atspre_g1int2uint_int_size;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp174, _Tmp175, _Tmp129, _Tmp184] call /*emit_f0ide*/ deleteActionInLoop_24;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp174] call /*emit_f0ide*/ libarma3__array_free
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
   /*ATSINSmove_void _*/[ _Tmp167] call /*emit_f0ide*/ text__free_text;
   /*ATSINSmove_void _*/[ _Tmp171] call /*emit_f0ide*/ text__free_text;
  _Tmp187 = [ _Tmp134, _Tmp133, _Tmp130, false] call /*emit_f0ide*/ libarma3__swapVariable_vt1;
  _Casefunx2 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(/*ATSCKptriscons*/ (not(isNil { _Tmp187 select 0 } )) ) then {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        } else {
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3 : {
        if(/*ATSCKptrisnull*/ ( isNil { _Tmp187 select 0 }) ) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 29945(line=721, offs=16) -- 30109(line=725, offs=17)");
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp189 = (_Tmp187 select 0);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp187);;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp189] call /*emit_f0ide*/ fn_support__free_request_support_vehicles_vt
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx2 /* emit_Casefunx */ , 1 ] call _Casefunx2 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
   /*ATSINSmove_void _*/[ _Tmp133] call /*emit_f0ide*/ text__free_text;
  _Tmp191 = [0, _Tmp129];
  _Tmpret127 = [ 1, _Tmp191 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret127;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ add_per_class_support_request_in_loop_21 = compileFinal {
  params ["_Env0", "_Arg0", "_Arg1", "_Arg2", "_Arg3", "_Arg4"];
//
// knd = 1
// var _Apy0
private _Apy0 = 0;
// var _Apy1
private _Apy1 = 0;
// var _Apy2
private _Apy2 = 0;
// var _Apy3
private _Apy3 = 0;
// var _Apy4
private _Apy4 = 0;
// var _Tmpret136
private _Tmpret136 = 0;
// var _Tmp137
private _Tmp137 = 0;
// var _Tmp138
private _Tmp138 = 0;
// var _Tmp140
private _Tmp140 = 0;
// var _Tmp141
private _Tmp141 = 0;
// var _Tmp142
private _Tmp142 = 0;
// var _Tmp143
private _Tmp143 = 0;
// var _Tmp144
private _Tmp144 = 0;
// var _Tmp145
private _Tmp145 = 0;
// var _Tmp146
private _Tmp146 = 0;
// var _Tmp147
private _Tmp147 = 0;
// var _Tmp148
private _Tmp148 = 0;
// var _Tmp149
private _Tmp149 = 0;
// var _Tmp150
private _Tmp150 = 0;
// var _Tmp151
private _Tmp151 = 0;
// var _Tmp153
private _Tmp153 = 0;
// var _Tmp156
private _Tmp156 = 0;
// var _Tmp158
private _Tmp158 = 0;
// var _Tmp159
private _Tmp159 = 0;
// var _Tmp160
private _Tmp160 = 0;
// var _Tmp161
private _Tmp161 = 0;
// var _Tmp163
private _Tmp163 = 0;
// var _Tmp164
private _Tmp164 = 0;
// var Funlab_sqf
private _Funlab_sqf = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  while {true} do {
    _Funlab_sqf = 0;
    // __patsflab_add_per_class_support_request_in_loop_21 /*ATSINSflab*/ ;
    _Tmp137 = [ _Arg4, _Arg3] call /*emit_f0ide*/ atspre_g1uint_eq_size;
    if (_Tmp137) then {
        _Tmpret136 = _Arg0;
      } // if-then
      else {
        _Tmp138 = [ _Arg2, _Arg4] call /*emit_f0ide*/ libarma3__array_vt_get1;
        _Casefunx1 /* emit_Casefunx */  = {
          params [ "_Casefun", "_Tmplab"];
          // switch(_Tmplab) {
          switch(_Tmplab) do
          {
            // ATSbranchseq_beg
            case 1 : {
              if(/*ATSCKptriscons*/ (not(isNil { _Tmp138 select 0 } )) ) then {
                 [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
              } else {
                 [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
              };
            };
            case 2 : {
/*emit2_branchlst rest-of-ATSINS*/              ; // ATSINSmove_void()
            };
            // ATSbranchseq_end
            // ATSbranchseq_beg
            case 3 : {
              if(/*ATSCKptrisnull*/ ( isNil { _Tmp138 select 0 }) ) then {
                systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 22923(line=590, offs=27) -- 26398(line=646, offs=30)");
              } else {
                 [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
              };
            };
            case 4 : {
/*emit2_branchlst rest-of-ATSINS*/              _Tmp140 = (_Tmp138 select 0);
/*emit2_branchlst rest-of-ATSINS*/              // ATSINSfreecon(_Tmp138);;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp145 = [ ] call /*emit_f0ide*/ libarma3__configFile;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp146 = [ "CfgVehicles"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp144 = [ _Tmp145, _Tmp146] call /*emit_f0ide*/ libarma3__bindConfigC;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp143 = [ _Tmp144, /* ATSSELfltrec */ (_Tmp140 select 0)] call /*emit_f0ide*/ libarma3__bindConfig;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp147 = [ "displayName"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp142 = [ _Tmp143, _Tmp147] call /*emit_f0ide*/ libarma3__bindConfigC;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp141 = [ _Tmp142] call /*emit_f0ide*/ libarma3__getText;
/*emit2_branchlst rest-of-ATSINS*/              _Casefunx2 /* emit_Casefunx */  = {
                params [ "_Casefun", "_Tmplab"];
                // switch(_Tmplab) {
                switch(_Tmplab) do
                {
                  // ATSbranchseq_beg
                  case 1 : {
                    if(/*ATSCKptriscons*/ (not(isNil { _Tmp141 select 0 } )) ) then {
                       [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
                    } else {
                       [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
                    };
                  };
                  case 2 : {
/*emit2_branchlst rest-of-ATSINS*/                    _Tmp148 = [ /* ATSSELfltrec */ (_Tmp140 select 0)] call /*emit_f0ide*/ text__copy
                  };
                  // ATSbranchseq_end
                  // ATSbranchseq_beg
                  case 3 : {
                    if(/*ATSCKptrisnull*/ ( isNil { _Tmp141 select 0 }) ) then {
                      systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 23775(line=605, offs=39) -- 23953(line=607, offs=76)");
                    } else {
                       [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
                    };
                  };
                  case 4 : {
/*emit2_branchlst rest-of-ATSINS*/                    _Tmp149 = (_Tmp141 select 0);
/*emit2_branchlst rest-of-ATSINS*/                    // ATSINSfreecon(_Tmp141);;
/*emit2_branchlst rest-of-ATSINS*/                    _Tmp148 = _Tmp149
                  };
                  // ATSbranchseq_end
                  default { assert(false); };
                }; // endcase
                //} // end-of-switch
              }; // endfun
              [ _Casefunx2 /* emit_Casefunx */ , 1 ] call _Casefunx2 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp151 = [ 0] call /*emit_f0ide*/ atspre_g1int2uint_int_size;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp150 = [ _Tmp151] call /*emit_f0ide*/ libarma3__array_vt_create;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp153 = [ "STR_support_place_vehicle"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Tmp150, _Tmp153] call /*emit_f0ide*/ libarma3__array_vt_pushBack;
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Tmp150, _Tmp148] call /*emit_f0ide*/ libarma3__array_vt_pushBack;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp156 = [ /* ATSSELfltrec */ (_Tmp140 select 2)] call /*emit_f0ide*/ text__pack_size_t;
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Tmp150, _Tmp156] call /*emit_f0ide*/ libarma3__array_vt_pushBack;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp158 = [ /* ATSSELfltrec */ (_Tmp140 select 1)] call /*emit_f0ide*/ text__pack_size_t;
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Tmp150, _Tmp158] call /*emit_f0ide*/ libarma3__array_vt_pushBack;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp159 = [ _Tmp150] call /*emit_f0ide*/ libarma3__format_localize;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp161 = [ /* ATSSELfltrec */ (_Tmp140 select 0)] call /*emit_f0ide*/ text__copy;
/*emit2_branchlst rest-of-ATSINS*/              _Tmp160 = [ _Env0, _Tmp159, fn_support__place_requested_vehicle_action, _Tmp161, 1.5, false, true] call /*emit_f0ide*/ libarma3__addAction;
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Tmp159] call /*emit_f0ide*/ text__free_text;
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Arg0, _Tmp160] call /*emit_f0ide*/ libarma3__array_pushBack
            };
            // ATSbranchseq_end
            default { assert(false); };
          }; // endcase
          //} // end-of-switch
        }; // endfun
        [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
        _Tmp164 = [ 1] call /*emit_f0ide*/ atspre_g1int2uint_int_size;
        _Tmp163 = [ _Arg4, _Tmp164] call /*emit_f0ide*/ atspre_g1uint_add_size;
        /* ATSINSmove_tlcal */ _Apy0 = _Arg0;
        /* ATSINSmove_tlcal */ _Apy1 = _Arg1;
        /* ATSINSmove_tlcal */ _Apy2 = _Arg2;
        /* ATSINSmove_tlcal */ _Apy3 = _Arg3;
        /* ATSINSmove_tlcal */ _Apy4 = _Tmp163;
        /* ATSINSargmove_tlcal */ _Arg0 = _Apy0;
        /* ATSINSargmove_tlcal */ _Arg1 = _Apy1;
        /* ATSINSargmove_tlcal */ _Arg2 = _Apy2;
        /* ATSINSargmove_tlcal */ _Arg3 = _Apy3;
        /* ATSINSargmove_tlcal */ _Arg4 = _Apy4;
        _Funlab_sqf = 1; /*ATSINSfgoto*/ // __patsflab_add_per_class_support_request_in_loop_21
         /*emit2_tailcalseqlst*/
      // if-else
      };
    if (_Funlab_sqf < 1) then { break; };
  }; // endwhile-fun
 /* ATSreturn */ _Tmpret136;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ deleteActionInLoop_24 = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 1
// var _Apy0
private _Apy0 = 0;
// var _Apy1
private _Apy1 = 0;
// var _Apy2
private _Apy2 = 0;
// var _Apy3
private _Apy3 = 0;
// var _Tmp177
private _Tmp177 = 0;
// var _Tmp178
private _Tmp178 = 0;
// var _Tmp180
private _Tmp180 = 0;
// var _Tmp181
private _Tmp181 = 0;
// var _Tmp182
private _Tmp182 = 0;
// var Funlab_sqf
private _Funlab_sqf = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  while {true} do {
    _Funlab_sqf = 0;
    // __patsflab_deleteActionInLoop_24 /*ATSINSflab*/ ;
    _Tmp177 = [ _Arg3, _Arg1] call /*emit_f0ide*/ atspre_g1uint_eq_size;
    if (_Tmp177) then {
        ; // ATSINSmove_void();
      } // if-then
      else {
        _Tmp178 = [ _Arg0, _Arg3] call /*emit_f0ide*/ libarma3__array_get1;
        _Casefunx1 /* emit_Casefunx */  = {
          params [ "_Casefun", "_Tmplab"];
          // switch(_Tmplab) {
          switch(_Tmplab) do
          {
            // ATSbranchseq_beg
            case 1 : {
              if(/*ATSCKptriscons*/ (not(isNil { _Tmp178 select 0 } )) ) then {
                 [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
              } else {
                 [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
              };
            };
            case 2 : {
/*emit2_branchlst rest-of-ATSINS*/              ; // ATSINSmove_void()
            };
            // ATSbranchseq_end
            // ATSbranchseq_beg
            case 3 : {
              if(/*ATSCKptrisnull*/ ( isNil { _Tmp178 select 0 }) ) then {
                systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 29162(line=702, offs=35) -- 29535(line=708, offs=55)");
              } else {
                 [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
              };
            };
            case 4 : {
/*emit2_branchlst rest-of-ATSINS*/              _Tmp180 = (_Tmp178 select 0);
/*emit2_branchlst rest-of-ATSINS*/               /*ATSINSmove_void _*/[ _Arg2, _Tmp180] call /*emit_f0ide*/ libarma3__removeAction
            };
            // ATSbranchseq_end
            default { assert(false); };
          }; // endcase
          //} // end-of-switch
        }; // endfun
        [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
        _Tmp182 = [ 1] call /*emit_f0ide*/ atspre_g1int2uint_int_size;
        _Tmp181 = [ _Arg3, _Tmp182] call /*emit_f0ide*/ atspre_g1uint_add_size;
        /* ATSINSmove_tlcal */ _Apy0 = _Arg0;
        /* ATSINSmove_tlcal */ _Apy1 = _Arg1;
        /* ATSINSmove_tlcal */ _Apy2 = _Arg2;
        /* ATSINSmove_tlcal */ _Apy3 = _Tmp181;
        /* ATSINSargmove_tlcal */ _Arg0 = _Apy0;
        /* ATSINSargmove_tlcal */ _Arg1 = _Apy1;
        /* ATSINSargmove_tlcal */ _Arg2 = _Apy2;
        /* ATSINSargmove_tlcal */ _Arg3 = _Apy3;
        _Funlab_sqf = 1; /*ATSINSfgoto*/ // __patsflab_deleteActionInLoop_24
         /*emit2_tailcalseqlst*/
      // if-else
      };
    if (_Funlab_sqf < 1) then { break; };
  }; // endwhile-fun
 // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_25 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret197
private _Tmpret197 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_25 /*ATSINSflab*/ ;
  _Tmpret197 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret197;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_26 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret198
private _Tmpret198 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_26 /*ATSINSflab*/ ;
  _Tmpret198 = [ _Arg0, /*emit_f0ide*/ f___patsfun_27, fn_addon__ensure_boss] call /*emit_f0ide*/ result_vb__withExcept;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret198;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_27 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret199
private _Tmpret199 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_27 /*ATSINSflab*/ ;
  _Tmpret199 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret199;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__initClient = compileFinal {
//
// knd = 0
// var _Tmp225
private _Tmp225 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_initClient /*ATSINSflab*/ ;
  _Tmp225 = [ ] call /*emit_f0ide*/ ext_libarma3_hasInterface;
  if (_Tmp225) then {
       /*ATSINSmove_void _*/[ ] call /*emit_f0ide*/ fn_support__addActions;
    } // if-then
    else {
      ; // ATSINSmove_void()
    // if-else
    };
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__initServer = compileFinal {
//
// knd = 0
// var _Tmp227
private _Tmp227 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_initServer /*ATSINSflab*/ ;
  _Tmp227 = [ ] call /*emit_f0ide*/ ext_libarma3_hasInterface;
  if (_Tmp227) then {
       /*ATSINSmove_void _*/[ ] call /*emit_f0ide*/ fn_support__addActions;
    } // if-then
    else {
      ; // ATSINSmove_void()
    // if-else
    };
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__free_request_support_vehicle_record_vt = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmp229
private _Tmp229 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_free_request_support_vehicle_record_vt /*ATSINSflab*/ ;
  _Tmp229 = /* ATSSELfltrec */ (_Arg0 select 0);
   /*ATSINSmove_void _*/[ _Tmp229] call /*emit_f0ide*/ text__free_text;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__free_request_support_vehicles_vt = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmp231
private _Tmp231 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_free_request_support_vehicles_vt /*ATSINSflab*/ ;
  _Tmp231 = /* ATSSELfltrec */ (_Arg0 select 1);
   /*ATSINSmove_void _*/[ _Tmp231, fn_support__free_request_support_vehicle_record_vt] call /*emit_f0ide*/ libarma3__array_vt_free;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__place_requested_vehicle_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var _Tmp250
private _Tmp250 = 0;
// var _Tmp251
private _Tmp251 = 0;
// var _Tmp252
private _Tmp252 = 0;
// var _Tmp253
private _Tmp253 = 0;
// var _Tmp254
private _Tmp254 = 0;
// var _Tmp258
private _Tmp258 = 0;
// var _Tmp260
private _Tmp260 = 0;
// var _Tmp261
private _Tmp261 = 0;
// var _Tmp262
private _Tmp262 = 0;
// var _Tmp264
private _Tmp264 = 0;
// var _Tmp265
private _Tmp265 = 0;
// var _Tmp266
private _Tmp266 = 0;
// var _Tmp268
private _Tmp268 = 0;
// var _Tmp269
private _Tmp269 = 0;
// var _Tmp270
private _Tmp270 = 0;
// var _Tmp272
private _Tmp272 = 0;
// var _Tmp273
private _Tmp273 = 0;
// var _Tmp274
private _Tmp274 = 0;
// var _Tmp276
private _Tmp276 = 0;
// var _Tmp277
private _Tmp277 = 0;
// var _Tmp279
private _Tmp279 = 0;
// var _Tmp280
private _Tmp280 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_place_requested_vehicle_action /*ATSINSflab*/ ;
   /*ATSINSmove_void _*/[ _Arg3] call /*emit_f0ide*/ text__free_text;
  _Tmp254 = [0, _Arg1];
  _Tmp253 = [ _Tmp254, /*emit_f0ide*/ f___patsfun_35, fn_addon__ensure_not_null] call /*emit_f0ide*/ result_vb__withExcept;
  _Tmp252 = [ _Tmp253, /*emit_f0ide*/ f___patsfun_36] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp251 = [ _Tmp252, fn_support__get_deployeable_support_vehicle] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Tmp250 = [ _Tmp251, /*emit_f0ide*/ confirm_vehicle_placement_33] call /*emit_f0ide*/ result_vb__bind_env_result_vt;
  _Casefunx1 /* emit_Casefunx */  = {
    params [ "_Casefun", "_Tmplab"];
    // switch(_Tmplab) {
    switch(_Tmplab) do
    {
      // ATSbranchseq_beg
      case 1 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp250 select 0) == 0)) then {
          _Tmp270 = (_Tmp250 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp258 = (_Tmp250 select 1);
           [ _Casefun, 2 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 2 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp260 = /* ATSSELfltrec */ (_Tmp258 select 1);
         [ _Casefun, 3 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 3 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp260 select 0) == 0)) then {
          _Tmp262 = _Tmp258;
        } else {
           [ _Casefun, 4 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 4 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp261 = (_Tmp260 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp260);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp250);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp274 = [ "STR_support_caller_null"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp273 = [ _Tmp274] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp273] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp273] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp250 select 0) == 0)) then {
          _Tmp270 = (_Tmp250 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp262 = (_Tmp250 select 1);
           [ _Casefun, 6 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 6 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp264 = /* ATSSELfltrec */ (_Tmp262 select 1);
         [ _Casefun, 7 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 7 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp264 select 0) == 1)) then {
          _Tmp266 = _Tmp262;
        } else {
           [ _Casefun, 8 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 8 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp265 = (_Tmp264 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp264);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp250);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp277 = [ "STR_persistentUserMarkers_only_commander_can_do_this"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp276 = [ _Tmp277] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp276] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp276] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp250 select 0) == 0)) then {
          _Tmp270 = (_Tmp250 select 1);
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp266 = (_Tmp250 select 1);
           [ _Casefun, 10 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 10 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp268 = /* ATSSELfltrec */ (_Tmp266 select 1);
         [ _Casefun, 11 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 11 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp268 select 0) == 2)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 32750(line=811, offs=5) -- 34039(line=841, offs=6)");
        } else {
           [ _Casefun, 12 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 12 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp269 = (_Tmp268 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp268);;
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp250);;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp280 = [ "STR_support_no_requestable_support_vehicle"] call /*emit_f0ide*/ text__pack_string;
/*emit2_branchlst rest-of-ATSINS*/        _Tmp279 = [ _Tmp280] call /*emit_f0ide*/ libarma3__localize;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp279] call /*emit_f0ide*/ libarma3__systemChat;
/*emit2_branchlst rest-of-ATSINS*/         /*ATSINSmove_void _*/[ _Tmp279] call /*emit_f0ide*/ text__free_text
      };
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 13 : {
        if(not(/*ATSCKpat_con1(*/(_Tmp250 select 0) == 1)) then {
          systemChat( "ATSINScaseof_fail " + "/build/a3u-btr/src/DATS/fn_support.dats: 32750(line=811, offs=5) -- 34039(line=841, offs=6)");
        } else {
/*emit2_branchlst rest-of-ATSINS*/          _Tmp270 = (_Tmp250 select 1);
           [ _Casefun, 14 ]  call _Casefun /*emit_Casefun2*/ ;
        };
      };
      case 14 : {
         [ _Casefun, 15 ]  call _Casefun /*emit_Casefun2*/ 
      };
      case 15 : {
/*emit2_branchlst rest-of-ATSINS*/        _Tmp272 = /* ATSSELfltrec */ (_Tmp270 select 1);
/*emit2_branchlst rest-of-ATSINS*/        // ATSINSfreecon(_Tmp250);;
/*emit2_branchlst rest-of-ATSINS*/        ; // ATSINSmove_void()
      };
      // ATSbranchseq_end
      default { assert(false); };
    }; // endcase
    //} // end-of-switch
  }; // endfun
  [ _Casefunx1 /* emit_Casefunx */ , 1 ] call _Casefunx1 /* emit_Casefunx */  /* emit_Casefunx2 */ 
;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ confirm_vehicle_placement_33 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret233
private _Tmpret233 = 0;
// var _Tmp234
private _Tmp234 = 0;
// var _Tmp235
private _Tmp235 = 0;
// var _Tmp236
private _Tmp236 = 0;
// var _Tmp237
private _Tmp237 = 0;
// var _Tmp238
private _Tmp238 = 0;
// var _Tmp247
private _Tmp247 = 0;
// var _Tmp248
private _Tmp248 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_confirm_vehicle_placement_33 /*ATSINSflab*/ ;
  _Tmp234 = /* ATSSELfltrec */ (_Arg0 select 1);
  _Tmp235 = /* ATSSELfltrec */ (_Arg0 select 0);
  _Tmp236 = /* ATSSELfltrec */ (_Tmp234 select 0);
  _Tmp237 = /* ATSSELfltrec */ (_Tmp234 select 1);
  _Tmp238 = [ /* ATSSELfltrec */ (_Tmp237 select 0)] call /*emit_f0ide*/ text__copy;
  _Tmp247 = [ "test"] call /*emit_f0ide*/ text__pack_string;
   /*ATSINSmove_void _*/[ /* ATSSELfltrec */ (_Tmp237 select 0), /*emit_f0ide*/ on_placed_34, _Tmp238, _Tmp247] call /*emit_f0ide*/ fn_addon__HR_GRG_fnc_confirmPlacement;
  _Tmp248 = [_Tmp235, _Tmp236];
  _Tmpret233 = [ 1, _Tmp248 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret233;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ on_placed_34 = compileFinal {
  params ["_Arg0", "_Arg1"];
//
// knd = 0
// var _Tmp241
private _Tmp241 = 0;
// var _Tmp242
private _Tmp242 = 0;
// var _Tmp244
private _Tmp244 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_on_placed_34 /*ATSINSflab*/ ;
  _Tmp241 = [ _Arg0] call /*emit_f0ide*/ libarma3__isNotNull;
  if (_Tmp241) then {
      _Tmp242 = [ "item is not null"] call /*emit_f0ide*/ text__pack_string;
       /*ATSINSmove_void _*/[ _Tmp242] call /*emit_f0ide*/ libarma3__systemChat;
       /*ATSINSmove_void _*/[ _Tmp242] call /*emit_f0ide*/ text__free_text;
    } // if-then
    else {
      _Tmp244 = [ "item is null"] call /*emit_f0ide*/ text__pack_string;
       /*ATSINSmove_void _*/[ _Tmp244] call /*emit_f0ide*/ libarma3__systemChat;
       /*ATSINSmove_void _*/[ _Tmp244] call /*emit_f0ide*/ text__free_text
    // if-else
    };
   /*ATSINSmove_void _*/[ _Arg1] call /*emit_f0ide*/ text__free_text;
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_35 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret255
private _Tmpret255 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_35 /*ATSINSflab*/ ;
  _Tmpret255 = [ 0, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret255;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_36 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret256
private _Tmpret256 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_36 /*ATSINSflab*/ ;
  _Tmpret256 = [ _Arg0, /*emit_f0ide*/ f___patsfun_37, fn_addon__ensure_boss] call /*emit_f0ide*/ result_vb__withExcept;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret256;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ f___patsfun_37 = compileFinal {
  params ["_Arg0"];
//
// knd = 0
// var _Tmpret257
private _Tmpret257 = 0;
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab___patsfun_37 /*ATSINSflab*/ ;
  _Tmpret257 = [ 1, _Arg0 ]/* emit2_ATSINSmove_con1 */;
/*emit_f0body_0 emit2_instr_ln*/  /* ATSreturn */ _Tmpret257;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__finish_support_request_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_finish_support_request_action /*ATSINSflab*/ ;
  ; // ATSINSmove_void();
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__addVehicleToSupport_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_addVehicleToSupport_action /*ATSINSflab*/ ;
  ; // ATSINSmove_void();
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__deleteVehicleFromSupport_action = compileFinal {
  params ["_Arg0", "_Arg1", "_Arg2", "_Arg3"];
//
// knd = 0
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_deleteVehicleFromSupport_action /*ATSINSflab*/ ;
  ; // ATSINSmove_void();
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function


/*fun*/
/*emit_f0ide*/ fn_support__main = compileFinal {
//
// knd = 0
// var Tmplab, Tmplab_sqf
private _Tmplab = 0;
private _Tmplab_sqf = 0;
//
  // __patsflab_main /*ATSINSflab*/ ;
  ; // ATSINSmove_void();
/*emit_f0body_0 emit2_instr_ln*/  // return/*_void*/;;
}; // end-of-function

atscc2sqf_unit_heap resize 1;
_this call fn_support__main;
//////
////// defined but not used: 
// fn_support__main
// fn_support__deleteVehicleFromSupport_action
// fn_support__addVehicleToSupport_action
// fn_support__finish_support_request_action
// f___patsfun_37
// f___patsfun_36
// f___patsfun_35
// on_placed_34
// confirm_vehicle_placement_33
// fn_support__place_requested_vehicle_action
// fn_support__free_request_support_vehicle_record_vt
// fn_support__initServer
// fn_support__initClient
// f___patsfun_27
// f___patsfun_26
// f___patsfun_25
// add_actions_verified_20
// get_support_vehicles_19
// fn_support__requestSupport_action
// f___patsfun_17
// f___patsfun_16
// f___patsfun_15
// f___patsfun_14
// f___patsfun_13
// f___patsfun_12
// f___patsfun_11
// f___patsfun_10
// f___patsfun_9
// f___patsfun_8
// removeAction_verified_7
// fn_support__exitSupportEditor_action
// f___patsfun_5
// f___patsfun_4
// f___patsfun_3
// add_actions_verified_2
// fn_support__supportEditor_action
////// called external functions: 
// ext_libarma3_hasInterface
////// called undefined functions: 
// libarma3__isNotNull
// fn_addon__HR_GRG_fnc_confirmPlacement
// libarma3__array_vt_free
// libarma3__array_get1
// atspre_g1uint_add_size
// libarma3__format_localize
// text__pack_size_t
// libarma3__array_vt_pushBack
// libarma3__array_vt_create
// text__copy
// libarma3__getText
// libarma3__bindConfig
// libarma3__bindConfigC
// libarma3__configFile
// libarma3__array_vt_get1
// atspre_g1uint_eq_size
// libarma3__array_free
// libarma3__array_count
// libarma3__swapVariable_vt1
// libarma3__array_pushBack
// libarma3__array_vt_count
// libarma3__array_create
// atspre_g1int2uint_int_size
// libarma3__borrowVariable_vt1
// libarma3__missionNamespace
// libarma3__getVariable1
// libarma3__removeAction
// libarma3__setVariable
// libarma3__systemChat
// result_vb__bind_env_result_vt
// result_vb__withExcept
// text__free_text
// libarma3__addAction
// libarma3__localize
// text__pack_string
// libarma3__player
// fn_addon__commander
// end-of-compilation-unit
//
//////
